### ISSUE TITLE
Hello there! Will there be a widescreen mod for the offline version of Dragon Quest X in the future?

### ISSUE THREAD

**Issue by smilingz1203** [Lyall/DQXISFix#1]
Will there be support for a widescreen mod for the offline version of Dragon Quest X in the future?

**Comment by Lyall** [comment]
No plans for that game I'm afraid.

**Comment by smilingz1203** [comment]
Well, although it's unfortunate, I still want to thank you for your support of the game's widescreen mode. I hope more widescreen mods will be released in the future.
